config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'

  resources :restaurants, only: [:new, :create, :index, :show] do
    resources :reviews, only: [:new, :create]
  end

  resources :categories, only: [:index, :show]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :restaurants, through: :restaurantcategories
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  has_many :categories, through: :restaurantcategories

  validates :name,    presence: true
  validates :address, presence: true
  validates :city,    presence: true
  validates :state,   presence: true
  validates :zip,     presence: true, length: { is: 5 }, numericality: true
end

app/models/restaurantcategories.rb
class RestaurantCategories < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :category
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  validates :restaurant, presence: true
  validates :body,       presence: true
  validates :rating,     presence: true, numericality: true,
    inclusion: { in: 1..5, message: "Must be between 1 - 5" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category    = Category.find(params[:id])
    @restaurants = Restaurant.where(category_id: params[:id])
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurant = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @ratings    = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      flash[:notice] = "Restaurant added successfully!"
      redirect_to @restaurant
    else
      flash[:error] = @restaurant.errors.full_messages.join(". ")
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :state, :zip, :description)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])

    if @review.save
      flash[:notice] = "Review added successfully"
      redirect_to restaurant_path(@review.restaurant)
    else
      flash[:error] = @review.errors.full_messages.join(". ")
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body).merge(restaurant: Restaurant.find(params[:restaurant_id]))
  end

end

app/views/categories/index.html.erb
<h1> Categories </h1>

<% @categories.each do |category| %>
  <%= link_to category.name, category_path(category) %><br>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %> Restaurants</h1>

<% @restaurants.each do |restaurant| %>
  <%= link_to restaurant.name, restaurant_path(restaurant) %><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Restaurant Reviews</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>

    <div class="navbar">
      <%= link_to 'View By Category', categories_path %>
    </div>
    <%= yield %>
  </body>

</html>

app/views/restaurants/index.html.erb
<h1> All Restaurants </h1>

<% @restaurant.each do |restaurant| %>
  <%= link_to restaurant.name, restaurant_path(restaurant) %><br>
  <%= restaurant.address %>     <br>
  <%= restaurant.city %>        <br>
  <%= restaurant.state %>       <br>
  <%= restaurant.zip %>         <br>
  <%= restaurant.description %> <br>
<% end %>

<%= link_to 'Add New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Add New Restaurant</h1>

<%= form_for @restaurant do |f| %>
  <%=f.label :name %>
  <%=f.text_field :name %>       <br>

  <%=f.label :address %>
  <%=f.text_field :address %>    <br>

  <%=f.label :city %>
  <%=f.text_field :city %>       <br>

  <%=f.label :state %>
  <%=f.text_field :state %>      <br>

  <%=f.label :zip %>
  <%=f.text_field :zip %>        <br>

  <%=f.label :description %>
  <%=f.text_area :description %> <br>

  <%= f.submit "Add Restaurant" %>
<% end %>

app/views/restaurants/show.html.erb
<h1>
  <%= @restaurant.name %>
</h1><br>
     <%= @restaurant.address %><br>
     <%= @restaurant.city %><br>
     <%= @restaurant.state %><br>
     <%= @restaurant.zip %><br>
     <%= @restaurant.description %><br>

<% @ratings.each do |rating| %>
  <%= rating.rating %><br>
  <%= rating.body %><br>
  <%= rating.created_at.strftime("%B %d %Y") %><br>
<% end %>

<%= link_to 'Add a Review', new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1> Review <%= @restaurant.name %></h1>

<%= form_for [@restaurant, @review] do |f| %>

  <%= f.label :rating %>
  <%= f.text_field :rating %>     <br>

  <%= f.label :body, 'Review' %>
  <%= f.text_area :body %>        <br>

  <%= f.submit 'Add Review' %>

<% end %>